run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - gosimple      # Simplify code
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code
    - gofmt         # Check for code formatting
    - goimports     # Check for import formatting
    - misspell      # Check for misspelled words
    - revive        # Drop-in replacement for golint
    - typecheck     # Type-check Go code
    - unparam       # Report unused function parameters
    - unconvert     # Remove unnecessary type conversions
    - goconst       # Find repeated strings that could be constants
    - dupl          # Code clone detection
    - godot         # Check for proper comment punctuation
    - goprintffuncname # Check printf-like function names
    - nolintlint    # Ensure nolint directives are properly formatted
    - gosec         # Security checker for Go code
    - bodyclose     # Check for HTTP response body close
    - gocritic      # Comprehensive Go source code linter

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: false  # Allow _ = in tests
    exclude-functions:
      - (os).RemoveAll  # Defer cleanup in tests is OK to ignore

  gofmt:
    simplify: true

  govet:
    enable-all: true
    disable:
      - shadow  # Disable shadow checking as it can be noisy
      - fieldalignment  # Disable struct field alignment - minor optimization

  revive:
    rules:
      - name: exported
        arguments:
          - "checkPrivateReceivers"
          - "disableStutteringCheck"

  misspell:
    locale: US

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  # Exclude some linters from running on tests files
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - goconst

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true
