version: "2"

run:
  timeout: 5m
  tests: true

formatters:
  enable:
    - gofmt         # Check for code formatting
    - goimports     # Check for import formatting
  settings:
    gofmt:
      simplify: true

linters:
  enable:
    - errcheck      # Check for unchecked errors
    - govet         # Vet examines Go source code
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Go static analysis
    - unused        # Check for unused code
    - misspell      # Check for misspelled words
    - revive        # Drop-in replacement for golint
    - unparam       # Report unused function parameters
    - unconvert     # Remove unnecessary type conversions
    - goconst       # Find repeated strings that could be constants
    - dupl          # Code clone detection
    - godot         # Check for proper comment punctuation
    - goprintffuncname # Check printf-like function names
    - nolintlint    # Ensure nolint directives are properly formatted
    - gosec         # Security checker for Go code
    - bodyclose     # Check for HTTP response body close
    - gocritic      # Comprehensive Go source code linter
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false  # Allow _ = in tests
      exclude-functions:
        - (os).RemoveAll  # Defer cleanup in tests is OK to ignore
    
    gosec:
      excludes:
        - G204  # Subprocess launched with variable - needed for script execution
        - G306  # File permissions - we need executable scripts

    govet:
      enable-all: true
      disable:
        - shadow  # Disable shadow checking as it can be noisy
        - fieldalignment  # Disable struct field alignment - minor optimization

    revive:
      rules:
        - name: exported
          arguments:
            - "checkPrivateReceivers"
            - "disableStutteringCheck"

    misspell:
      locale: US

    dupl:
      threshold: 200

    goconst:
      min-len: 3
      min-occurrences: 3
  exclusions:
    rules:
      - path: '(.+)_test\.go'
        linters:
          - dupl
          - goconst

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
